# this is your main configration file you wil have to define variables here

resource "local_file" "devops" {
        filename = "/root/variables/terrafrom"
        content = "jay bajarang bali, jay veer bhadra"
}

resource "local_file" "devops_var" {
        filename = var.filename
        content = var.content

  # this your variables file  here you define your variables

variable "filename"  {
        default = "/root/variables/automated.txt"
}

variable "content" {
        default = "this is generated by automation"
}

=================================================================================================

# how to create config map in terraform variables
# this is the variables file 

variable "filename"  {
        default = "/root/variables/automated.txt"
}

variable "content" {
        default = "this is generated by automation"
}

variable "devops_op_trainer" {}

variable "content_map" {
type = map
default = {
content1 = "this is the first content1"
content2 = "this is the secound contain2"
}
}


# this is the main file

resource "local_file" "devops" {
        filename = "/root/variables/terrafrom"
        content = var.content_map["content1"]
}

resource "local_file" "devops_var" {
        filename = var.filename
        content = var.content_map["content2"]
}

output "devops_op_trainer" {
value = var.devops_op_trainer
}


=============================================================================================================================

# this is the variable of using list
# this is the varable file

variable "filename"  {
        default = "/root/variables/automated.txt"
}

variable "content" {
        default = "this is generated by automation"
}

variable "devops_op_trainer" {}

variable "content_map" {
type = map
default = {
content1 = "this is the first content1"
content2 = "this is the secound contain2"
}
}

variable "file_list" {
type = list
default = ["/root/variables/file_1.txt","/root/variables/file_2.txt"]
}


# this is the main configration file

root@ip-172-31-35-67:~/variables# cat main.tf 
resource "local_file" "devops" {
        filename = var.file_list[0]
        content = var.content_map["content1"]
}

resource "local_file" "devops_var" {
        filename = var.file_list[1]
        content = var.content_map["content2"]
}

output "devops_op_trainer" {
value = var.devops_op_trainer
}


================================================================================================================

# how to use object in terraform
# variable file
variable "filename"  {
        default = "/root/variables/automated.txt"
}

variable "content" {
        default = "this is generated by automation"
}

variable "devops_op_trainer" {}

variable "content_map" {
type = map
default = {
content1 = "this is the first content1"
content2 = "this is the secound contain2"
}
}

variable "file_list" {
type = list
default = ["/root/variables/file_1.txt","/root/variables/file_2.txt"]
}

variable "aws_ec2_object" {
  type = object ({
        name = string
        instances = number
        keys = list(string)
        ami = string
})

default = {
        name = "test_ec2_instance"
        instances = 4
        keys = ["key1.pem","key2.pem"]
        ami = "ubuntu-afr33"
}
}

# this is the main configration file

resource "local_file" "devops" {
        filename = var.file_list[0]
        content = var.content_map["content1"]
}

resource "local_file" "devops_var" {
        filename = var.file_list[1]
        content = var.content_map["content2"]
}

output "devops_op_trainer" {
value = var.devops_op_trainer
}

output "aws_ec2_info" {
value = var.aws_ec2_object
}
