# this is your main configration file you wil have to define variables here

resource "local_file" "devops" {
        filename = "/root/variables/terrafrom"
        content = "jay bajarang bali, jay veer bhadra"
}

resource "local_file" "devops_var" {
        filename = var.filename
        content = var.content

  # this your variables file  here you define your variables

variable "filename"  {
        default = "/root/variables/automated.txt"
}

variable "content" {
        default = "this is generated by automation"
}
